### ISSUE TITLE
Smaller Monitor Issues

### ISSUE THREAD

**Issue by netzeln** [netzeln/WorkoutGenerator#17]
on a smaller/ laptop screen  the second set exercises are covered by the lower black bar again.

**Comment by iamJRD** [comment]
Gahhhh! I thought I had that fixed earlier! I'll take a peak at it when I get home.

**Comment by tstratton-ut** [comment]
We worked so hard on fixing that too!

**Comment by iamJRD** [comment]
I feel like something probably got accidentally deleted in a merge. I'll attempt to track it down but I'll be surprised if anybody finds that tomorrow. They haven't ever looked at anything like that in code reviews before so I doubt the teachers will even check it out. Ha.

**Comment by iamJRD** [comment]
I was able to fix the footer covering stuff at any viewpoint but it seemed to make the instructions column not be responsive width-wise in mobile form. We can take a peak at it tomorrow but again, I doubt it's the biggest of problems considering all that we have done on this. 

**It is currently not merged with the master branch.**
